---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: grafana-ns
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAk8N7viO8kE61If7pwwj/omwb0/eqria1+R1rsLqYKZ1KDVu+3gsDmDcjd8VVnaWeK8ZDyEYiFQRGZgL85cxCV6adyKbhDEgENv96peCNK7mNpFGLo4Ni8hxlQPRVu0j3HmBs35+foFeUZ45KM71Oxpl0xpVKwTtCmO886NcHbvte7nyGryxwpFLTvB+8TFrU0TCwwPf/eE43Q/4Gk7uyb1vMPnx4Y97PlK9MWCb0aspkAokpfjcaeXUQ2zMYWL3kGzp7wKUfR3y7bSBdxhot0xvV4v240vu1hYo/5ktJLtOpeYZZapgn2VY04xwzBRXqsmJZlsXemK58+Z2TWSOLLCfazZtiJHk1BAFCQ3QhdJtOQYk1ohbVwf67RvHUsa1B3tIJE/LkLeig7T16mBC8QLp9Lyp8lgHp+Nc5kC2dfBxcmLKkKuvpMMGFk2moHPgmeLTNmzmJL4sT8Z3G4moGK7MvY7c2H6gFJtg3WqnI1wMgm1i365AHSzZn2g6IOZCrB+BtXyZwQQwf2XGWDklUaDrAiY8HuaEpUcFkkr8aDd1arkJ4d73bejyBW5TB1522mTIU/FgaR1Uhjcxo+PANO8gBnxBYNrFv6jO1dEogp1Qi46lmha+xXJR/S3W9PGKIuqwBfhJBFKSkWo+UXzN+qaHJWPIqWV7svvcYvV7gvBleR32dwHArphtb34EwGthV9OpZPCg==
    GF_SECURITY_ADMIN_USER: AgBDCmDxDkM8mRl4Cc7Ofw2Oxbp+XKPcHSTdxCShJdJfdK5IQ64HUVw5w2Yea+J7P4qDUd1PuPVv5rudslybTzoxQxU6TKEVVS6QUvA8z2BTdnmC+jnu5mKC/vkbTNgqXyS+cBbRngXpL+KINbH9rrZljpZxcUBaQVJsoHfOeVq70uXwpSDa5hoMFEkpjO8yxM1ZsFaz0EcSNrTCSi3HkXRFg9ivd92sc3NS1RrHsKMRlWZuoDEWq3A74kbA5Ekvpp6fias5zUSCRERLLscqr+Xdvk10KoKU7R30eESsXp/RHkqip9pDYSalD0TRGUHTUkqL8UgW9RvMu73MaUszcEmxHSEeki2O60vbMZOvJmTFzrgs7xmefsV3k9c68Xpj3K3zF6t9f6daQZJw62FztBMap7FIKQLrNMwjP3l87WU9UDCzuO56JB2niozbzyhwW6gL9LqR/lmwETKab8jTt4yHl+FLgEj+k18XzhCxVXnR0bs07hOymh0tbZG/qkAVkajnHxDN3jliACeSWiQraYMGFM1BjXGBljhfjV7gEKl2GhxOfMW0iDAjJUAI8Cw4ImLzZRzP2uYpZsi6PM9aPJeAdw2pcycRQ8zDPJ2RtZpl6sg7/cAxgtS7WbA1gdt8/1/swWGaitN+I7OGaJBbnVri853fqay1ZcNS3r7nEfBZo4aavXTOnF0VTr/yhnDlt1Zhxsb/Tw==
  template:
    metadata:
      name: grafana-secret
      namespace: grafana-ns
