---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: grafana-ns
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgBAVG2zK/anzHb5fQbdQlNP9uliJNHMO0yzODxMZ1aGGnEWJsa18Q1xrTh1xzX0BrM/OQSFtiQzSN5ByaAip/JGJehhylbMCOStC8PHoPiVv8RF6gSdAL40MJaVJBsBopTgbB4Acbq7SF8tsxJptiXIzHJ1X8PDUGmz8uUHu0uFGnCiAVCFNKWPAHgzHKEThGEcXDbRXfyPJ9kgH4pytr+AKwMBMb2WybfNyQmr1oG1FNSo9zscgQ03Iq91mwmpUN0YO9aU0wTbVhiAVy2Xg9Alcew7h+53iCcJH7xw0bXdrJFcnRIvHWdgDmRg3xVLA0iH2dktt56O6OGOpyw0dFSmSRO9fILN4ESfgcoIRnNyNPdWF0r3yZJLmUcOfl9boBUzc4c13OweHeTlfEW1rqlPvCL85SUQW0mpW4/yOyWj9BzLzHFDA0T+sP8pyVBjLWkd41LzmtmFIZ9jAvRNf2xHj4LAgSmbZaBeWC9//gaGNAEPqRBMPG7ZMcEIctmmKOTt9Q0iUly/dwyX2AkfXhVz+IXjmwWkegwL0GsD+3P7zOscqYo7w5orM3bNebkV3b/fvr2iQ371N8ds453vBB6X8X/O2TH+i6moM5cEXLxIk0YxhlvohCUsDlUD7UJ3bxTtXmCI3wEKvfS5e1NmtVneXy3fY6L3aN6XnZaqO6BGYh4AzltkEIkxB1Sd9JXnP/i1yPNueQ==
    GF_SECURITY_ADMIN_USER: AgCfSyQ+VF/JbecpfOShcB5dGi0id76fgEZJMnNUvZXB8gcVmxFsKh4yE00g1HeI6nx67qhYagBb1nYhh8t782IAC6/C5eXgKq/u7um/dLBv8AlKk4XSvfd+0bltvVJvprbqZe4hrldaSkSSzwYIx9u1n37nq3XfUsL6AQ+HjVdhuWY+BqbeDJEltQJdWkfxhUlzQ8KFmxR6zdmTkOcnFSqvB4s+QwojnkZErukEQHiQ440fP8udDTcIEOPAqduOuaVydjPsxcvItcZKn2qM3YnSFdIVN5Ao3JrdS3/Vz2tmrIhpCbhdB4kd2bvDmbRUQux8xzlWwdZKMJZFq2WfY1NUcYQ4hNuRlW9mb0xX2njg4GTj75ePv5UehFDty7MeUk/fJja8ctSVdAh9Pb+qyokIwL2yZEHnxp4dJJtzypjlhjAGNogXP2jDkSsQLqMgOKyDA+KCNyo8TXY84OJp0ixA0uf/9Q08LoYBiZNhEkAe8qcRXFDPa/f+ArLkkboYCjW7JX5fMJQLAyA9HOMNS4eJt5+tYbsPSl+kssh+LT1UWP1LBXvjrQGHQOI/nSAt6jLMPz3QmjAoD9tP4vtxT16UFSweRaKwX1o3vd2U41sEY+zmqwXPIaFNTB0zQwXcfwP2wLcSBKOEmTPSlUZ9JwFRB6wCU81hRP4lj0r9Z5aT/hgJHhnFJ95Uac6RHeo/CRG7r20U8w==
  template:
    metadata:
      name: grafana-secret
      namespace: grafana-ns
