apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thmanyah-ingress
  namespace: ingress-ns
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/enable-access-log: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: thmanyah.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-external
                port:
                  number: 3000