---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-secret
  namespace: prometheus-ns
spec:
  encryptedData:
    slack_api_url: AgBMC5bSAVI2QzqQINyelbftuMq7x7idZxranwyJYlEGdBxhq6lLTw15EesRQs+q09nXXqFz1kK+5BGNt89NEXrAWItDCurOev9GxlarryTKuDjpP47UQSDWk454LGzImgcI9m+Azxm/5cZISsA+AKlR0jVVUJRHZ7z+UeO02XzCyL++lWxPCs5u8okx4T8phuI29IaQI6wCcYCOTaxD7bbc+kKkFoQot9TLdX6VR3W1T2/EtgSpbJJ02xO3E1DumXI47ARLWl2X0KZQOgUlRaWDRsc2wUdxggfZHlwbcV6XCEDEZDRK0DkpQYRysGh9VIZuMar0FDx0Aj19McblOmd9Amuw7Nf0k1xjsCLHnbbdvbvC8C4ijuGpfIauYtr+pVl9Bcwzjne7AJPLAFt3hep2FzvnTLEmdbqzP3rxQklnxgzB4NLra8DIwY/e/viuOxQ91BsxoyvpdnS4w8YdOvGThK7bq5/v56ViziqL5a37OiwDI0P38L+LNcap4KTVH62niO2HeFnllW0rJVviCgH01gbK1a3t9UWrs/5WdPf/XJuPBcnXNtV2FCaefm6sCIuok8UWUw2T4rtpRz73aJTxZxQy+P+aJYfwIOHTAc09DV84UUWkJw0o4i3xPHOuUdRWprOKZD3N8GxsxRbTLaZvYRFOxSFdkdqQ8/znNuQ/Cu1nzxMSNXaTFEkDiUwr3vIIbMfelW7suHA+/nF1Bx8TPOD7Z3wlFsWD1+qgaDUQtyhrlfFh/FRppQfcEE9a8VSFbsEMvROq9b/CaO1f7iGZEqgwMsuQnLX96TSTT1JOAA4=
  template:
    metadata:
      name: alertmanager-secret
      namespace: prometheus-ns
